name: Kernel Builder Redmi 9T juice based on AOSPA

on: [push]

env:
  SOURCE: https://github.com/ShelbyHell/sunrise_kernel_juice -b topaz
  TOOLCHAIN: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initialize environment
         run: |
            sudo apt update
            sudo apt install -y build-essential libncurses5-dev bzip2 git
       - name: Clone kernel source and compiler
         run: |
            mkdir kernel
            cd kernel
            git clone $SOURCE source
            git clone $TOOLCHAIN toolchain
       - name: Integrate KernelSU
         run: |
            cd kernel/source
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
       - name: Compile KERNEL
         run: |
            cd kernel/source
            export CROSS_COMPILE=/home/runner/work/kernelsu-xiaomi-juice/kernelsu-xiaomi-juice/kernel/toolchain/bin/aarch64-linux-
            export ARCH=arm64
            make ranchu64_defconfig
            make -j$(nproc --all)
       - name: Upload Image.gz
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/work/kernelsu-xiaomi-juice/kernelsu-xiaomi-juice/kernel/source/arch/arm64/boot/*.gz
