name: Kernel Builder Redmi 9T juice based on AOSPA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: pokon548/sunrise_kernel_juice
        ref: topaz-kernelsu
        path: source
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Integrate KernelSU
      run: |
        cd source
        git clone https://github.com/tiann/KernelSU
        cd KernelSU
        git stash && git pull
        cd ../
        cp -r KernelSU/kernel drivers/kernelsu

        echo "[+] Add kernel su driver to Makefile"

        echo "obj-y += kernelsu/" >> drivers/Makefile

        echo "[+] Done."
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        KERNEL_PATH: source
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: vendor/bengal-perf_defconfig
        image: Image.gz-dtb