name: Kernel Builder Xiaomi 10 Ultra

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Integrate KernelSU
      run: |
        
        
        
        wget http://mirrors.ustc.edu.cn/debian/pool/main/e/elfutils/debuginfod_0.183-1~bpo10%2B1_amd64.deb
        sudo dpkg -i ./debuginfod_0.183-1~bpo10+1_amd64.deb
        
        wget http://mirrors.ustc.edu.cn/debian/pool/main/e/elfutils/debuginfod_0.183-1_amd64.deb
        sudo dpkg -i ./debuginfod_0.183-1_amd64.deb

        

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: /home/runner/work/kernelsu-xiaomi-cas-online/kernelsu-xiaomi-cas-online/source/arch/arm64/boot/Image

