name: Kernel Builder Redmi 9T juice based on AOSPA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: pokon548/sunrise_kernel_juice
        ref: topaz-kernelsu
        path: source

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        KERNEL_PATH: source
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: vendor/bengal-perf_defconfig
        image: Image.gz-dtb
    - name: Upload Image.gz
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: source/arch/arm64/boot/*.gz