name: Kernel Builder Xiaomi 10 Ultra

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Integrate KernelSU
      run: |
        
        
        sudo apt install git-core gnupg flex bison build-essential zip curl build-essential tree
        
        git clone https://github.com/CoolestEnoch/xiaomi-10-ultra-kernel
        
        mv xiaomi-10-ultra-kernel source
  
        cd source
      
        echo "[+] Append kernel params to kprobes"
        echo "CONFIG_KPROBES=y" >> arch/arm64/configs/vendor/cas_defconfig
        echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/vendor/cas_defconfig
        echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/vendor/cas_defconfig

        git clone https://github.com/tiann/KernelSU
        cd KernelSU
        git stash && git pull
        cd ..
        cp -r KernelSU/kernel drivers/kernelsu

        echo "[+] Add kernel su driver to Makefile"

        echo "obj-y += kernelsu/" >> drivers/Makefile

        echo "[+] Done."
        
        cd ..
        
        git clone https://github.com/CoolestEnoch/kernel-su-xiaomi-cas
        
        mkdir gcc
        mv kernel-su-xiaomi-cas/gcc/ ./gcc
        rm -rf kernel-su-xiaomi-cas
        
        tree ./gcc

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: /home/runner/work/kernelsu-xiaomi-cas-online/kernelsu-xiaomi-cas-online/source/arch/arm64/boot/Image

